# Generated by Django 5.1.4 on 2024-12-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_types',
            field=models.CharField(choices=[('Applicant', 'Applicant'), ('Recruiter', 'Recruiter')], max_length=20),
        ),
    ]
