# Generated by Django 5.1.4 on 2024-12-24 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cert_image', models.ImageField(upload_to='certifications/')),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Skill Category',
                'verbose_name_plural': 'Skill Categories',
            },
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='No bio available'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cgpa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='resume',
            field=models.FileField(default='resumes/default_resume.pdf', upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='work_experience',
            field=models.TextField(default='No work experince available'),
        ),
        migrations.AddField(
            model_name='profile',
            name='certification',
            field=models.ManyToManyField(related_name='profiles', to='users.certification'),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(to='users.skill'),
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='users.skillcategory'),
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(fields=('name', 'category'), name='unique_skill_category'),
        ),
    ]
