# Generated by Django 5.1.4 on 2024-12-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_certification_skill_skillcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='I am Hari...'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.CharField(default='ABC institute of technology', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(default='TamilNadu/Chennai', max_length=255),
        ),
    ]
