# Generated by Django 5.1.4 on 2024-12-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profile_cgpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Applicant', 'Applicant'), ('Recruiter', 'Recruiter')], default='Applicant', max_length=20),
        ),
    ]
