# Generated by Django 5.1.4 on 2024-12-26 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_rename_comapny_webiste_employer_company_webiste'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer',
            old_name='company_webiste',
            new_name='company_website',
        ),
    ]
