# Generated by Django 5.1.4 on 2024-12-26 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_jobskills_alter_job_job_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='application_deadline',
            field=models.DateField(default=datetime.date(2024, 12, 30)),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.CharField(choices=[('0-2', '0-2 years'), ('3-6', '3-6 years'), ('7-10', '7-10 years'), ('10+', '10+ years')], default='0-2', max_length=5),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_category',
            field=models.CharField(default='Development', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills_required',
            field=models.ManyToManyField(to='jobs.jobskills'),
        ),
    ]
