# Generated by Django 5.1.4 on 2024-12-26 12:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_job_application_deadline_alter_job_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='last_date_to_apply',
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='job',
            name='posted_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
