# Generated by Django 5.1.4 on 2024-12-27 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_rename_skills_required_job_skills_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='skills',
        ),
        migrations.DeleteModel(
            name='JobSkills',
        ),
    ]
