# Generated by Django 5.1.4 on 2024-12-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_job_job_related_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='employer_image',
            field=models.ImageField(default='emp_default.jpg', upload_to='employer_profile_pic/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_category',
            field=models.CharField(default='Development/It', max_length=100),
        ),
    ]
