# Generated by Django 5.1.4 on 2024-12-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_employer_employer_image_alter_job_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='company_logo',
            field=models.ImageField(default='company_default.png', upload_to='company_logo/'),
        ),
    ]
