# Generated by Django 5.1.4 on 2024-12-28 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_alter_employer_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='company_logo',
            field=models.ImageField(blank=True, default='company_default.png', null=True, upload_to='company_logo/'),
        ),
    ]
