# Generated by Django 5.1.4 on 2024-12-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_alter_employer_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='company_logo',
            field=models.ImageField(blank=True, default='default_logo.png', null=True, upload_to='company_logo/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='work_mode',
            field=models.CharField(choices=[('WFO', 'Work from Office'), ('hybrid', 'Hybrid'), ('remote', 'Remote')], default='wfo', max_length=10),
        ),
    ]
