# Generated by Django 5.1.4 on 2024-12-30 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_job_max_salary_alter_job_min_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.CharField(choices=[('0-1', '0-1 years'), ('1-3', '1-3 years'), ('3-5', '3-5 years'), ('5-7', '5-7 years'), ('7-10', '7-10 years'), ('10+', '10+ years')], default='0-2', max_length=5),
        ),
    ]
