# Generated by Django 5.1.4 on 2025-01-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0023_jobapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplicationSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_application_skills', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job_related_skills',
            field=models.ManyToManyField(blank=True, related_name='job_applications', to='jobs.jobapplicationskills'),
        ),
    ]
