# Generated by Django 5.1.4 on 2025-01-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0025_rename_job_related_skills_jobapplication_jobapplication_skills'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='jobapplicationskills',
            constraint=models.UniqueConstraint(fields=('job_application_skills',), name='unique_jobapp_skills'),
        ),
    ]
