# Generated by Django 5.1.4 on 2025-01-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0032_review_rate_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rate_review',
            field=models.IntegerField(choices=[(1, 'Bad'), (2, 'Poor'), (3, 'Good'), (4, 'Average'), (5, 'Excellent')], default=3),
        ),
    ]
