# Generated by Django 5.1.4 on 2025-01-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0033_alter_review_rate_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_skills', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_related_skills',
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='skills', to='jobs.jobskills'),
        ),
    ]
